### PR TITLE
Added a program: RemoveDuplicatesFromSortedArray.java

### PR DESCRIPTION
**Pull request by thecoderkd**
LeetCode Level Easy
Topic Array
[Link to problem](https://leetcode.com/problems/remove-duplicates-from-sorted-array)

### CODE REVIEW

**Comment by thecoderkd** [comment]
Hey @Sid672 Can you please verify and add the "Hacktoberfest" label to your repository to make it eligible for hactoberfest.
Thank you!

**Comment by Sid672** [comment]
@thecoderkd, I am also checking which repos. are valid for contribution in hacktoberfest and which are not. If my project is applicable then I will add the tags. If you have any important link please share.

**Review by Sid672 — CHANGES_REQUESTED** [review]
Please add your GitHub user name and problem link in the comments at the top of the program.

**Comment by Sid672** [comment]
Format:
```
/*
* Author: Github name;
* Problem Link: Link:
*/
```

**Comment by thecoderkd** [comment]
@Sid672 To make it eligible for hacktoberfest, you just have to add the "hacktoberfest" tag in the repository
It should show up like this
image

**Comment by thecoderkd** [comment]
Made the changes, please check @Sid672 
And add the hacktoberfest tag, thanks!

**Comment by Sid672** [comment]
@thecoderkd thanks for the comments but to add the label I need to add documentation about hacktoberfest. So I am unable to add labels now. 
But for you have some repo of hacktoberfest you can contribute to these repos:
1) https://github.com/Sushreesatarupa/DSA-cpp-Hacktoberfest2021
2) https://github.com/iamdevvalecha/Hacktoberfest-21-Open-First-PR

**Comment by Sid672** [comment]
Good Luck!

**Comment by thecoderkd** [comment]
@Sid672 I dont think you need to add the documentation. Just add the label, I have tried it as well

**Comment by thecoderkd** [comment]
Just add a topic called hacktoberfest, simple :)

**Comment by thecoderkd** [comment]
Hey @Sid672 can you please add?

**Comment by Sid672** [comment]
@thecoderkd I know every pull request is important in hacktoberfest. After our discussion on hactoberfest label, I join the official discord group of Hacktoberfest. In the chat, the event manger told that quality pull requests don't include DSA based PR it will count in progress but after the mature period ends, it will be not counted. 

So it's better to find some good open source projects where you can participate and give some quality contribution. If you have any further questions related to hacktoberfest please join the official discord group of Hacktoberfest.

Link of discord group: https://discord.gg/hacktoberfest

**Pull request merged**
