### PR TITLE
Question Add to LeetCode(Medium)

### PR DESCRIPTION
**Pull request by parth-gpt**

### CODE REVIEW

**Review by Sid672 — CHANGES_REQUESTED** [review]
Please delete the unnecessary files and add your GitHub username on top of the java program file.

**Comment by parth-gpt** [comment]
Deleted the extra files.

**Review by Sid672 — CHANGES_REQUESTED** [review]
Nice work but you need to delete two more (.Ds_Store) files.

**Comment by parth-gpt** [comment]
Yeah for those files I am not getting any option to delete. That is why..

**Review by Sid672 — APPROVED** [review]
Okay, good work!

**Pull request merged**
