### PR TITLE
added documentation comments

### PR DESCRIPTION
**Pull request by diksharai9**

### CODE REVIEW

**Review by diksharai9 — COMMENTED** [review]
okay, I will correct them.

**Review by Sid672 — COMMENTED** [review]
Good work @diksharai9!

**Comment by Sid672** [comment]
@diksharai9 you have done good work! 
Now you should participate in some open-source programs. 
Here is a link: https://hacktoberfest.digitalocean.com/
If you are interested in some good first issue use: https://goodfirstissue.dev/
Good Luck!

**Comment by diksharai9** [comment]
> @diksharai9 you have done good work!
> Now you should participate in some open-source programs.
> Here is a link: https://hacktoberfest.digitalocean.com/
> If you are interested in some good first issue use: https://goodfirstissue.dev/
> Good Luck!

thankyou

**Pull request merged**
